'use client';

import React from 'react';
import { Card } from '../common/Card';
import { Activity, ShieldCheck, UserPlus, Zap } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';

export function ActivityTimeline() {
  // Mock data for the activity timeline
  const activities = [
    {
      id: 1,
      type: 'system',
      title: 'Model Retraining Completed',
      description: 'Model v2.4.1 deployed successfully with 98.2% accuracy.',
      timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      icon: Zap,
      color: 'text-info',
      bgColor: 'bg-info-muted'
    },
    {
      id: 2,
      type: 'security',
      title: 'API Key Generated',
      description: 'New API key generated by admin@voxguard.internal',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      icon: ShieldCheck,
      color: 'text-genuine',
      bgColor: 'bg-genuine-muted'
    },
    {
      id: 3,
      type: 'user',
      title: 'New Analyst Added',
      description: 'Jane Doe was added to the organization.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      icon: UserPlus,
      color: 'text-text-primary',
      bgColor: 'bg-surface-elevated'
    },
    {
      id: 4,
      type: 'system',
      title: 'Daily Report Generated',
      description: 'System automatically generated the 24h summary.',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      icon: Activity,
      color: 'text-text-secondary',
      bgColor: 'bg-surface-hover'
    }
  ];

  return (
    <Card className="h-full flex flex-col">
      <div className="mb-6">
        <h2 className="text-lg font-medium text-text-primary">System Activity</h2>
        <p className="text-sm text-text-secondary mt-1">Audit log of system events</p>
      </div>

      <div className="flex-1 overflow-y-auto">
        <div className="relative border-l border-border ml-3 space-y-6 pb-4">
          {activities.map((activity) => {
            const Icon = activity.icon;
            return (
              <div key={activity.id} className="relative pl-6">
                <div className={`absolute -left-3 top-0 h-6 w-6 rounded-full flex items-center justify-center border-2 border-background ${activity.bgColor}`}>
                  <Icon size={12} className={activity.color} />
                </div>
                <div className="flex flex-col">
                  <div className="flex items-center justify-between gap-4">
                    <h3 className="text-sm font-medium text-text-primary">{activity.title}</h3>
                    <span className="text-xs text-text-muted shrink-0">
                      {formatDistanceToNow(new Date(activity.timestamp), { addSuffix: true })}
                    </span>
                  </div>
                  <p className="text-xs text-text-secondary mt-1">
                    {activity.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </Card>
  );
}
