"""Initial schema

Revision ID: 9a30ddb5385a
Revises: 
Create Date: 2026-08-29 13:12:01.588505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a30ddb5385a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vg_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='vg_user_role', create_constraint=True), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vg_users_email'), 'vg_users', ['email'], unique=True)
    op.create_table('vg_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vg_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('vg_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('caller_id', sa.String(length=50), nullable=True),
    sa.Column('caller_name', sa.String(length=255), nullable=True),
    sa.Column('call_type', sa.Enum('LIVE', 'UPLOADED', name='vg_call_type', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FLAGGED', name='vg_call_status', create_constraint=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['vg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vg_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('threshold_low', sa.Float(), nullable=False),
    sa.Column('threshold_medium', sa.Float(), nullable=False),
    sa.Column('threshold_high', sa.Float(), nullable=False),
    sa.Column('threshold_critical', sa.Float(), nullable=False),
    sa.Column('notify_in_app', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('auto_escalate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vg_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.Enum('GENUINE', 'SUSPICIOUS', 'CLONED', name='vg_verdict', create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('spectral_score', sa.Float(), nullable=True),
    sa.Column('prosody_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spectrogram_path', sa.String(length=500), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['vg_calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vg_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='vg_severity', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'FALSE_POSITIVE', name='vg_alert_status', create_constraint=True), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['vg_users.id'], ),
    sa.ForeignKeyConstraint(['analysis_id'], ['vg_analysis_results.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['vg_calls.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['vg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('otps')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('otps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='otps_pkey')
    )
    op.drop_table('vg_alerts')
    op.drop_table('vg_analysis_results')
    op.drop_table('vg_configurations')
    op.drop_table('vg_calls')
    op.drop_table('vg_api_keys')
    op.drop_index(op.f('ix_vg_users_email'), table_name='vg_users')
    op.drop_table('vg_users')
    # ### end Alembic commands ###
