'use client';

import React, { useEffect, useState, useMemo } from 'react';
import { PageHeader } from '@/components/layout/PageHeader';
import { AlertTable } from '@/components/alerts/AlertTable';
import { AlertFilters } from '@/components/alerts/AlertFilters';
import { AlertDetail } from '@/components/alerts/AlertDetail';
import { useAlertStore } from '@/stores/alertStore';
import { Alert } from '@/types/call';

export default function AlertsPage() {
  const { alerts, fetchAlerts, acknowledgeAlert, resolveAlert, isLoading } = useAlertStore();
  
  const [filters, setFilters] = useState({
    status: '',
    severity: '',
    search: ''
  });
  
  const [page, setPage] = useState(1);
  const itemsPerPage = 10;
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);

  useEffect(() => {
    // For Phase 3, we fetch all and filter client side for responsiveness, 
    // or we could pass filters to API if backend supports it.
    // Backend supports status and severity query params.
    const params: any = { limit: 100 }; // Get up to 100 recent alerts
    if (filters.status) params.status = filters.status;
    if (filters.severity) params.severity = filters.severity;
    
    fetchAlerts(params);
  }, [fetchAlerts, filters.status, filters.severity]);

  const handleFilterChange = (key: string, value: string) => {
    setFilters(prev => ({ ...prev, [key]: value }));
    setPage(1); // Reset page on filter change
  };

  const clearFilters = () => {
    setFilters({ status: '', severity: '', search: '' });
    setPage(1);
  };

  // Client-side search filtering (since backend might not have text search)
  const filteredAlerts = useMemo(() => {
    let result = alerts;
    if (filters.search) {
      const q = filters.search.toLowerCase();
      result = result.filter(a => 
        a.call_id.toLowerCase().includes(q) || 
        a.message.toLowerCase().includes(q)
      );
    }
    return result;
  }, [alerts, filters.search]);

  // Pagination
  const totalPages = Math.ceil(filteredAlerts.length / itemsPerPage) || 1;
  const paginatedAlerts = filteredAlerts.slice(
    (page - 1) * itemsPerPage,
    page * itemsPerPage
  );

  return (
    <div className="flex flex-col h-full animate-in fade-in duration-300">
      <PageHeader 
        title="Alert Management" 
        description="Review and respond to security alerts generated by the analysis engine."
      />

      <AlertFilters 
        filters={filters} 
        onChange={handleFilterChange} 
        onClear={clearFilters} 
      />

      <div className="flex-1">
        <AlertTable 
          alerts={paginatedAlerts}
          isLoading={isLoading}
          onAcknowledge={acknowledgeAlert}
          onResolve={resolveAlert}
          onViewDetails={setSelectedAlert}
          pagination={{
            currentPage: page,
            totalPages,
            onPageChange: setPage,
            totalItems: filteredAlerts.length
          }}
        />
      </div>

      <AlertDetail 
        alert={selectedAlert}
        isOpen={!!selectedAlert}
        onClose={() => setSelectedAlert(null)}
        onAcknowledge={acknowledgeAlert}
        onResolve={resolveAlert}
      />
    </div>
  );
}
